---

- name: apt installing uwsgi build requirements
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - build-essential
    - gcc
  become: yes
  tags:
    - uwsgi-emperor

- name: installing uwsgi
  command: "python{{ python_version }} -m pip install -U uwsgi"

- name: setting uwsgi binary path
  set_fact: uwsgi_binary="/usr/local/bin/uwsgi"

- name: copying uwsgi default file
  copy:
    dest: /etc/default/uwsgi-emperor
    src: etc/default/uwsgi-emperor
    owner: root
    group: www-data
  become: yes

- name: copying uwsgi configration files
  copy:
    dest: /etc/
    src: etc/uwsgi-emperor
    owner: root
    group: www-data
  become: yes

- name: creating init.d file for uwsgi
  template:
    dest: /etc/init.d/uwsgi-emperor
    src: etc/init.d/uwsgi-emperor.j2
    owner: root
    group: www-data
    mode: 755
  become: yes
  notify: reload uwsgi-emperor

- name: creating the vassal directory
  file:
    path: /etc/uwsgi-emperor/vassals
    state: directory
    owner: www-data
    group: www-data
  become: yes

- name: creating the log directory
  file:
    path: /var/log/uwsgi
    state: directory
    owner: www-data
    group: www-data
  become: yes

- name: making sure uwsgi-emperor is running
  service:
    name: uwsgi-emperor
    state: restarted
    enabled: yes
  become: yes
